version: "2.1"
services:
  dd-angular_app:
    # Build the container using the Dockerfile
    image: angular-movie
    build: ./
    restart: always
    ports:
      - 4200:4200

  movie-service:
    environment:
      MYSQL_URL: movie-mysql
    image: movie-image
    restart: always
    build: moviecruiserserver
    ports: 
      - 8787:8787

  movie-mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: root
    image: mysql
    restart: always
    ports:
      - 3308:3306
